baseURL = "https://rozawa.tk"
languageCode = "pl-PL"
title = "Solidarni z Rożawą"

# Metadata
[params]
  author = "RiotKit"
  description = "Przeciwko wojnie w Syrii! Solidarni z Rożawą i ludnością cywilną!"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "Przeciwko wojnie w Syrii!"
  byline = "Solidarni z Rożawą i ludnością cywilną!"

# Services section
[params.services]
  enable = true
  title = "Czym jest Rożawa?"
  subtitle = "To niezależny, wielokulturowy region w północnej i południowo-wschodniej Syrii oparty na **systemie demokracji bezpośredniej i demokracji uczestniczącej**."

  [[params.services.item]]
    weight = "A"
    title = "Demokracja"
    description = "W Rożawie ludzie decydują wspólnie. Powoływane są komitety lokalne dające prawo głosu każdemu obywatelowi, komitety wybierają delegatów, którym przekazują decyzje dalej, organizowane są referenda.<br><small><a href=\"https://pl.wikipedia.org/wiki/Demokratyczny_konfederalizm\" target==\"blank\">Czytaj więcej</a></small>"

  [[params.services.item]]
    weight = "B"
    title = "Kooperatywy"
    description = "Funkcjonuje sporo kooperatyw, czyli miejsc, w których **pracownicy zarządzają miejscem pracy wspólnie** - wszyscy są szefami. <br><small><a href=\"https://mesopotamia.coop/\" target=\"blank\">Zobacz listę części z nich.</a></small>"

  [[params.services.item]]
    weight = "C"
    title = "Równe prawa"
    description = "Mężczyźni i kobiety mają takie same prawa - prawa głosu, prawo do edukacji. Zarówno mężczyźni jak i kobiety walczą w Powszechnych Jednostkach Obrony - kobiet jest nieznacznie więcej w jednostkach od mężczyzn."

  [[params.services.item]]
    weight = "D"
    title = "Poszanowanie różnorodności"
    description = "Na terenie Rożawy żyją m.in. Kurdowie, Arabowie, Ormianie, Asyryjczycy, Chaladejczycy. Wyznawane są odłamy Chrześcijaństwa, Islamu, a także innych religii. Szanowane są prawa mniejszości."


# Welcome section
[params.welcome]
  enable = true
  title = "Co mogę zrobić?"
  subtitle = "Rożawa potrzebuje aby media całego świata mówiły o niej, nie tylko w kotekście wojny, ale także i w kontekście demokracji bezpośredniej i rewolucji społecznej"
  description = "<ul class=\"what-can-i-do\"><li>&nbsp;Napisz artykuł do gazety</li><li>&nbsp;Stwórz grafiki informacyjne i opublikuj na portalach społecznościowych</li><li>&nbsp;Zoorganizuj pikietę informacyjną pod konsulatem lub ambasadą Turcji, lub Rosji w sprawie zaprzestania ingerencji w Syrię</li><li>&nbsp;Porozmawiaj o tym z rodziną i ze znajomymi</li><li>&nbsp;Udostępnij tę stronę na portalach społęcznościowych</li></ul>"

